# Generated by Django 4.2 on 2023-05-06 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0002_avatar'),
    ]

    operations = [
        migrations.DeleteModel(
            name='avatar',
        ),
    ]
