# Generated by Django 4.2 on 2023-05-07 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(default='default_avatar.jpg', upload_to='avatars'),
        ),
    ]
