# Generated by Django 4.2 on 2023-04-28 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0002_remove_blogs_updated_at_blogs_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='image',
        ),
        migrations.AddField(
            model_name='blogs',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='blogs',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
