# Generated by Django 4.2.1 on 2023-05-07 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blogs_avatar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='avatar',
        ),
        migrations.CreateModel(
            name='Avatar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(default='default_avatar_b.jpg', upload_to='avatars')),
                ('blog', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='blogs.blogs')),
            ],
        ),
    ]
