# Generated by Django 4.2.1 on 2023-05-07 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_remove_blogs_avatar_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='avatar',
            field=models.ImageField(default='blog_imagen/default_imagen.jpg', upload_to='blog_imagen/'),
        ),
        migrations.DeleteModel(
            name='Avatar',
        ),
    ]
